@startuml
class Користувач
class Адміністратор
class Платіж
class Рахунок
class Послуга
class Квитанція
class Підприємство
class Тариф
class БанківськаКартка
class Сповіщення

Адміністратор --|> Користувач
Користувач --> Платіж
Користувач --> Рахунок
Платіж --> Квитанція
Платіж --> БанківськаКартка
Рахунок --> Послуга
Послуга --> Підприємство
Підприємство --> Тариф
Платіж --> Сповіщення
@enduml