services:
  bill-service:
    build: ./bill_service
    ports:
      - "8001:8000"

  payment-service:
    build: ./payment_service
    ports:
      - "9001:8000"
    depends_on:
      - bill-service
